<?php
/*
 * @category Magento-2 UserWay Widget Module
 * @package Userway_Widget
 * @copyright Copyright (c) 2021
 */

/**
 * @var \Userway\Widget\Block\Widget $block
 */
?>

<?php if ($block->isStoreWidgetEnabled()): ?>
    <script>
        window._userway_config = {
            account: "p5sFJEtw3C"
        }
    </script>
    <script src="https://cdn.qa.userway.dev/widget.js"></script>
<?php endif; ?>
