<script>
    require([
        'jquery'
    ], function ($) {

        const MESSAGE_ACTION_TOGGLE = 'WIDGET_TOGGLE';
        const MESSAGE_ACTION_SIGNUP = 'WIDGET_SIGNUP';

        const request = (url, data) => {
            return new Promise((resolve, reject) => {
                $.ajax({
                    url,
                    data,
                    type: 'POST',
                    dataType: 'json'
                }).done(data => resolve(data))
                    .fail(err => reject(err));
            })
        }

        const requestUpdateAccountState = (url, recordId, accountId, state) => request(url, {accountId, recordId, state});
        const requestToggleState = (url, recordId, state) => request(url, {state, recordId});

        const isPostMessageAccountToggleAction = (postMessage) => {
            return postMessage.data !== undefined
                && postMessage.data.action
                && postMessage.data.action === MESSAGE_ACTION_TOGGLE
        }

        const isPostMessageSignupAction = (postMessage) => {
            return postMessage.data !== undefined
                && postMessage.data.action
                && postMessage.data.action === MESSAGE_ACTION_SIGNUP
        }

        $(document).ready(function () {
            const selector = document.getElementById('userway-frame');
            const frameContentWindow = selector.contentWindow;
            const {url, toggleurl: toggleUrl, id} = selector.dataset;

            window.addEventListener('message', postMessage => {
                if (postMessage.source !== frameContentWindow) {
                    return;
                }

                console.log('postMessage -> ', postMessage);
                console.log('postMessage data -> ', postMessage.data);
                console.log('postMessage isPostMessageSignupAction -> ', isPostMessageSignupAction(postMessage));
                console.log('postMessage isPostMessageAccountToggleAction -> ', isPostMessageAccountToggleAction(postMessage));

                if (isPostMessageAccountToggleAction(postMessage)) {
                    const state = postMessage.data.state ? 1 : 0;
                    requestToggleState(toggleUrl, id, state)
                        .then(res => console.log(res))
                        .catch(err => console.error(err));
                } else if (isPostMessageSignupAction(postMessage)) {
                    const state = postMessage.data.state ? 1 : 0;
                    requestUpdateAccountState(url, id, postMessage.data.account, state)
                        .then(res => console.log(res))
                        .catch(err => console.error(err));
                }
            });
        });
    })
</script>
