<?php
/*
 * @category Magento-2 UserWay Widget Module
 * @package Userway_Widget
 * @copyright Copyright (c) 2021
 */

/**
 * @var \Userway\Block\Frame $block
 */
?>

<style>
    #userway-frame {
        width: 100%;
        height: 1180px;
        border: none;
    }
</style>

<div class="frame-container">
    <iframe id="userway-frame" scrolling="no" src="<?= $block->getFrameUrl() ?>"></iframe>
</div>
