name: Stable-Release

on:
  push:
    branches:
      - master
    paths:
      - '!.VERSION'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          root: ".VERSION"
          regex_pattern: "(\\d+\\.\\d+\\.\\d+)"
          tag_prefix: "Stable-v"
